# Site settings
title: Patanamon (Pick) Thongtanunam 
email: patanamon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Patanamon Thongtanunam 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patanamon.com" # the base hostname & protocol for your site
twitter_username: none
github_username:  none

# Build settings
markdown: kramdown

future: true

collections:
  papers:
    output: true
    permalink: /publications/:title/
  theses:
    output: true
    permalink: /publications/:title/